a = list("Hello World", "Hi", seq(1,10, by=2), TRUE)
print(a)
b = list(c("Jan","Feb","Mar"), list("Hello", "All", 365))
names(b) = c("Month_Name","Inner_List")
print(b)
print(b[2])
print(b$Month_Name)
print(length(b))
b[3] = "New Element"
print(length(b))
print(b)

c = list(1)
class(c)
d = list(2,3,4)
v1 = unlist(c)
class(v1)
v2 = unlist(d)
print(v1+v2)